name: Bundle Release App

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  bundle-release-app:
    runs-on: macos-11
    environment: Beta
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo $ENCODED_STRING | base64 -d > nxtbuz_release

      - name: Decode Google Services Json
        id: decode_google_services_json
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_STRING | base64 -d > app/google-services.json

      - name: Build App
        run: |
          touch local.properties
          echo "lta.account.key.debug=${{ secrets.LTA_ACCOUNT_KEY_DEBUG }}" >> local.properties
          echo "lta.account.key.release=${{ secrets.LTA_ACCOUNT_KEY_RELEASE }}" >> local.properties
          echo "google.maps.api.key.debug=${{ secrets.GOOGLE_MAPS_API_KEY_DEBUG }}" >> local.properties
          echo "google.maps.api.key.release=${{ secrets.GOOGLE_MAPS_API_KEY_RELEASE }}" >> local.properties
          echo "keystore.file.path=$GITHUB_WORKSPACE/nxtbuz_release" >> local.properties
          echo "keystore.password=${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}" >> local.properties
          echo "keystore.key.alias=${{ secrets.RELEASE_KEYSTORE_KEY_ALIAS }}" >> local.properties
          echo "keystore.key.password=${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}" >> local.properties
          ./gradlew bundleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Built files
          path: app/build/outputs